language: python
cache: pip
python:
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements
script:
  - pytest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
